name: bettervanilla
main: com.daveestar.bettervanilla.Main
version: 1.0.3
api-version: 1.20
authors: ["daveestar"]
commands:
  waypoints:
    aliases: [wp]
    description: Set or Remove waypoints. And display a list of all available waypoints.
    usage: /waypoints
    permission: bettervanilla.waypoints
  playtime:
    aliases: [pt]
    description: Get the playtime of either yourself or of another user.
    usage: /playtime
    permission: bettervanilla.playtime
  ping:
    description: Get the ping of either yourself or of another user.
    usage: /ping
    permission: bettervanilla.ping
  invsee:
    description: See the inventory of another player.
    usage: /invsee
    permission: bettervanilla.invsee
  timer:
    description: Resume, Pause, Reset the Timer.
    usage: /timer
    permission: bettervanilla.timer
  adminhelp:
    description: Get help for admin commands of better vanilla.
    usage: /adminhelp
    permission: bettervanilla.adminhelp
  settings:
    aliases: [set]
    description: A command to toggle different global settings.
    usage: /settings
    permission: bettervanilla.settings
  help:
    description: Get help for better vanilla.
    usage: /help
  togglelocation:
    aliases: [tl]
    description: Turn on/off action bar location.
    usage: /togglelocation
    permission: bettervanilla.togglelocation
  togglecompass:
    aliases: [tc]
    description: Turn on/off bossbar compass.
    usage: /togglecompass
    permission: bettervanilla.togglecompass
  lastdeath:
    aliases: [ld]
    description: Navigate to the last death point
    usage: /lastdeath
    permission: bettervanilla.lastdeath
