name: bettervanilla
main: com.daveestar.bettervanilla.Main
version: 1.6.0
api-version: 1.21
authors: ["daveestar"]
commands:
  waypoints:
    aliases: [wp]
    description: Open the waypoint GUI or manage waypoints with subcommands.
    usage: /waypoints
    permission: bettervanilla.waypoints
  playtime:
    aliases: [pt]
    description: Display your playtime or another player's playtime.
    usage: /playtime
    permission: bettervanilla.playtime
  ping:
    description: Display your ping or that of another player.
    usage: /ping
    permission: bettervanilla.ping
  invsee:
    description: View another player's inventory.
    usage: /invsee
    permission: bettervanilla.invsee
  timer:
    description: Control the timer (resume, pause, reset).
    usage: /timer
    permission: bettervanilla.timer
  adminhelp:
    description: Show all admin commands for BetterVanilla.
    usage: /adminhelp
    permission: bettervanilla.adminhelp
  settings:
    aliases: [set]
    description: Open the settings menu.
    usage: /settings
    permission: bettervanilla.settings
  help:
    description: Show in-game help for BetterVanilla.
    usage: /help
  togglelocation:
    aliases: [tl]
    description: Enable or disable action-bar location.
    usage: /togglelocation
    permission: bettervanilla.togglelocation
  togglecompass:
    aliases: [tc]
    description: Enable or disable boss-bar compass.
    usage: /togglecompass
    permission: bettervanilla.togglecompass
  deathpoints:
    aliases: [dp]
    description: Open the death-points GUI.
    usage: /deathpoints
    permission: bettervanilla.deathpoints
  permissions:
    aliases: [perms]
    description: Manage player and group permissions.
    usage: /permissions
    permission: bettervanilla.permissions
