name: bettervanilla
main: com.daveestar.bettervanilla.Main
version: 1.7.0
api-version: 1.21
authors: ["daveestar"]
commands:
  waypoints:
    aliases: [wp]
    description: Open the waypoint GUI or manage waypoints with subcommands.
    usage: /waypoints
    permission: bettervanilla.waypoints
  playtime:
    aliases: [pt]
    description: Opens playtime gui and displays your playtime or another player's playtime.
    usage: /playtime
    permission: bettervanilla.playtime
  ping:
    description: Display your ping or that of another player.
    usage: /ping
    permission: bettervanilla.ping
  invsee:
    description: View another player's inventory.
    usage: /invsee
    permission: bettervanilla.invsee
  timer:
    description: Control the timer (resume, pause, reset).
    usage: /timer
    permission: bettervanilla.timer
  adminhelp:
    description: Show all admin commands for BetterVanilla.
    usage: /adminhelp
    permission: bettervanilla.adminhelp
  settings:
    aliases: [set]
    description: Open the settings menu.
    usage: /settings
    permission: bettervanilla.settings
  help:
    description: Show in-game help for BetterVanilla.
    usage: /help
  togglelocation:
    aliases: [tl]
    description: Enable or disable action-bar location.
    usage: /togglelocation
    permission: bettervanilla.togglelocation
  togglecompass:
    aliases: [tc]
    description: Enable or disable boss-bar compass.
    usage: /togglecompass
    permission: bettervanilla.togglecompass
  deathpoints:
    aliases: [dp]
    description: Open the death-points GUI.
    usage: /deathpoints
    permission: bettervanilla.deathpoints
  permissions:
    aliases: [perms]
    description: Manage player and group permissions.
    usage: /permissions
    permission: bettervanilla.permissions
  backpack:
    aliases: [bp]
    description: Open your backpack.
    usage: /backpack
    permission: bettervanilla.backpack
  message:
    aliases: [msg]
    description: Send a private message to another player.
    usage: /msg <player> <message>
    permission: bettervanilla.msg
  reply:
    aliases: [r]
    description: Reply to the last private message.
    usage: /r <message>
    permission: bettervanilla.msg
  vanish:
    description: Toggle vanish mode.
    usage: /vanish
    permission: bettervanilla.vanish
  kick:
    description: Kick a player from the server.
    usage: /kick <player> [reason]
    permission: bettervanilla.kick
  ban:
    description: Ban a player from the server.
    usage: /ban <player> [reason] [seconds]
    permission: bettervanilla.ban
  unban:
    description: Remove a player's ban.
    usage: /unban <player>
    permission: bettervanilla.unban
  mute:
    description: Mute a player.
    usage: /mute <player> [reason] [seconds]
    permission: bettervanilla.mute
  unmute:
    description: Remove a player's mute.
    usage: /unmute <player>
    permission: bettervanilla.unmute
