name: bettervanilla
main: com.daveestar.bettervanilla.Main
version: 1.0.0
api-version: 1.19
authors: ['daveestar']
commands:
  waypoints:
    description: Set or Remove waypoints. And display a list of all available waypoints.
    usage: /waypoints [set|remove] <name> [confirm]
    permission: bettervanilla.waypoints
  ping:
    description: Get the ping of either yourself or of another user.
    usage: /ping [name]
    permission: bettervanilla.ping
  invsee:
    description: See the inventory of another player.
    usage: /invsee <name>
    permission: bettervanilla.invsee
  help:
    description: Get help for better vanilla.
    usage: /help
  togglelocation:
    description: Turn on/off action bar location.
    usage: /togglelocation
  playerhead:
    description: Get a head from a player
    usage: /playerhead <name>
