name: bettervanilla
main: com.daveestar.bettervanilla.Main
version: 1.10.1
api-version: 1.21
authors: ["daveestar"]
commands:
  help:
    description: Show in-game help for BetterVanilla.
    usage: /help
  adminhelp:
    description: Show all admin commands for BetterVanilla.
    usage: /adminhelp
  permissions:
    aliases: [perms]
    description: Manage player and group permissions.
    usage: /permissions
  settings:
    aliases: [set]
    description: Open the settings menu.
    usage: /settings
  vanish:
    aliases: [v]
    description: Toggle vanish mode.
    usage: /vanish
  invsee:
    aliases: [is]
    description: View another player's inventory.
    usage: /invsee
  kick:
    description: Kick a player from the server.
    usage: /kick
  ban:
    description: Ban a player from the server.
    usage: /ban
  unban:
    description: Remove a player's ban.
    usage: /unban
  mute:
    description: Mute a player.
    usage: /mute
  unmute:
    description: Remove a player's mute.
    usage: /unmute
  timer:
    aliases: [t]
    description: Control the timer (resume, pause, reset).
    usage: /timer
  playtime:
    aliases: [pt]
    description: Opens playtime gui and displays your playtime or another player's playtime.
    usage: /playtime
  waypoints:
    aliases: [wp]
    description: Open the waypoint GUI or start player or coords navigation.
    usage: /waypoints
  deathpoints:
    aliases: [dp]
    description: Open the death-points GUI.
    usage: /deathpoints
  ping:
    aliases: [p]
    description: Display your ping or that of another player.
    usage: /ping
  sit:
    aliases: [s]
    description: Sit down anywhere on the ground.
    usage: /sit
  backpack:
    aliases: [bp]
    description: Open your backpack.
    usage: /backpack
  message:
    aliases: [msg]
    description: Send a private message to another player.
    usage: /msg
  reply:
    aliases: [r]
    description: Reply to the last private message.
    usage: /r
