name: bettervanilla
main: com.daveestar.bettervanilla.Main
version: 1.0.0
api-version: 1.19
authors: ['daveestar']
commands:
  waypoints:
    description: Set or Remove waypoints. And display a list of all available waypoints.
    usage: /waypoints [set|remove] <name> [confirm]
    permission: bettervanilla.waypoints
