name: Build & Package (BetterVanilla)

on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build .jar
      run: mvn -B package --file pom.xml

    - name: Publish .jar to Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -DskipTests -Doverwrite=true
      env:
        GITHUB_TOKEN: ${{ github.token }}
    
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.build.outputs.version }}
        release_name: Release v${{ steps.build.outputs.version }}
        draft: false
        prerelease: false

    - name: Set version output
      id: build
      run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
